Add TLS domains endpoint support
opencredo/go-fastly pull request #29
Opened 2021-01-25 15:31 UTC by wjam

2021-01-25 15:44 UTC, bengesoff requested changes

2021-01-25 15:44 UTC, bengesoff commented on fastly/custom_tls_domain.go
> +		switch t := reflect.TypeOf(value).String(); t {
Have you tried `switch value.(type)`? Couldn't see any reason why that wouldn't work when trying it on the subscriptions

2021-01-25 15:44 UTC, bengesoff commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
I'm not sure these are needed. `jsonapi` seems to accept the raw `TLSActivation` structs and only populate the `primary` field when it is specified as a `relation`. I'm doing something similar on the subscriptions side of things:
```go
// TLSSubscription represents a managed TLS certificate
type TLSSubscription struct {
	ID                   string            `jsonapi:"primary,tls_subscription"`
	CertificateAuthority string            `jsonapi:"attr,certificate_authority"`
	State                string            `jsonapi:"attr,state"`
	CreatedAt            *time.Time        `jsonapi:"attr,created_at,iso8601"`
	UpdatedAt            *time.Time        `jsonapi:"attr,updated_at,iso8601"`
	Configuration        *TLSConfiguration `jsonapi:"relation,tls_configuration"`
	TLSDomains           []*TLSDomain      `jsonapi:"relation,tls_domains"`
}
```

And when I deserialise the response into these, it correctly uses the `TLSConfiguration` and `TLSDomain` structs, only populating the ID fields as you'd expect. Kinda weird behaviour but avoids all the extra structs

2021-01-25 15:52 UTC, bengesoff commented
I've just pushed a commit as an example for my comments: https://github.com/opencredo/go-fastly/commit/f85f999a13b814ff8311677572eeca8729a4f915

Let me know if I've missed something/you disagree on anything

2021-01-25 16:02 UTC, wjam commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
I'm of the opinion that the types used shouldn't expose fields that aren't actually valid for that endpoint. For example, the `ID` field shouldn't be present on the struct used to send a POST request as that should only be filled in by the server. It's also odd having an attribute, that according to the struct type is mandatory rather than optional - a pointer, be the nil value of the type instead.

2021-01-25 16:19 UTC, bengesoff commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
I agree it's a weird pattern, but I wonder if it's the best of the two evils to use the `jsonapi` "idiomatic" way in the interest of consistency? For example the custom TLS part of the SDK does the same thing, and the [first example on the `jsonapi` README](https://github.com/google/jsonapi#example) has this pattern for its relations too. So while it's definitely weird, and not particularly nice, it is at least documented and consistent. If we do use separate "relationship" structs and override the `jsonapi` suggested model, we should probably update the other parts of the SDK with their APIs using `jsonapi` as well. What do you and @trentrosenbaum think?

2021-01-25 16:20 UTC, wjam commented on fastly/custom_tls_domain.go
> +		switch t := reflect.TypeOf(value).String(); t {
Can't think of a reason why it wouldn't work, and it also avoids casting by using `switch t := value.(type)`

2021-01-25 17:05 UTC, trentrosenbaum commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
I think we should follow the suggested patten and align this custom TLS Domain along with the other implemented features of the Customer TLS.

2021-01-26 08:53 UTC, wjam commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
Changed the list TLS domain to use the existing structs, although this means that the subscription API will now present the problem to users about precisely _what_ fields they should actually be filling in when they create a subscription

2021-01-26 08:55 UTC, wjam commented on fastly/custom_tls_domain.go
> +type TLSActivationRelationship struct {
Note that the use of `jsonapi:"relation` within the API so far is minimal, so what ever we decide here will become the de facto standard by sheer weight of numbers

2021-01-26 09:47 UTC, bengesoff commented on fastly/fixtures/custom_tls_domain/list.yaml
> +    body: '{"data":[{"id":"a-real-tld.example","type":"tls_domain","relationships":{"tls_activations":{"data":[]},"tls_certificates":{"data":[{"id":"6RltCYkOfFfzPVitOyLCnV","type":"tls_certificate"}]
Not quite sure what we want to do here but I noticed some other test fixtures had the IDs removed or replaced with `CERTIFICATE_ID` or something. Is that something we want to do too? Doesn't seem like it'd be a problem to leave it in

2021-01-26 09:48 UTC, bengesoff commented on fastly/custom_tls_domain.go
> +	FilterTLSCertificateID  string
Could be nice to add some comments to these fields to save having to look them up in the API docs

2021-01-26 09:49 UTC, bengesoff approved these changes
Few minor questions but otherwise looks good to go

2021-01-26 11:09 UTC, wjam commented on fastly/fixtures/custom_tls_domain/list.yaml
> +    body: '{"data":[{"id":"a-real-tld.example","type":"tls_domain","relationships":{"tls_activations":{"data":[]},"tls_certificates":{"data":[{"id":"6RltCYkOfFfzPVitOyLCnV","type":"tls_certificate"}]
All of the data was test data added by me and no longer exists, now that I remembered to destroy the test data, so I don't see any harm in including this information?

2021-01-26 11:11 UTC, wjam commented on fastly/custom_tls_domain.go
> +	FilterTLSCertificateID  string
The docs may not match reality - for example, the docs say that sort `Accepts created_at (ascending sort order) or -created_at (descending)` when in reality it supports `id` and `tls_activations.created_at`

2021-01-26 11:13 UTC, bengesoff commented on fastly/fixtures/custom_tls_domain/list.yaml
> +    body: '{"data":[{"id":"a-real-tld.example","type":"tls_domain","relationships":{"tls_activations":{"data":[]},"tls_certificates":{"data":[{"id":"6RltCYkOfFfzPVitOyLCnV","type":"tls_certificate"}]
I don't see any harm either - just noticed that some other tests had seemed to omit it. Fine to leave it in 👍🏼

2021-01-26 11:15 UTC, bengesoff commented on fastly/custom_tls_domain.go
> +	FilterTLSCertificateID  string
Hahaha ok that's weird! Well, it's information that someone would have to discover the hard way but up to you 😂

2021-01-26 11:17 UTC, bengesoff commented
Looks good to me 👌🏼

2021-01-26 11:18 UTC, wjam commented on fastly/custom_tls_domain.go
> +	FilterTLSCertificateID  string
I've added documentation to the struct, fields and function but omitted details on precise values of certain fields.

2021-01-26 11:18 UTC, merged